const withNextIntl = require('next-intl/plugin')('./src/i18n/request.ts')

const standaloneRuntimeIncludes = [
  './public/**/*',
  './messages/**/*',
  './openapi.json',
  './package.json',
  './scripts/feishu-director-brain.mjs',
  './scripts/install-aiworker-director-brain.sh',
  './scripts/verify-shared-runtime-install-gate.mjs',
  './scripts/lib/feishu-director-brain.mjs',
  './scripts/lib/runtime-safe-offline-queue.mjs',
  './scripts/lib/shared-deployment-lock.sh',
  './openclaw-plugins/aiworker-director-brain/index.js',
  './openclaw-plugins/aiworker-director-brain/openclaw.plugin.json',
  './openclaw-plugins/aiworker-director-brain/package.json',
  './openclaw-plugins/aiworker-director-brain/lib/**/*',
  './openclaw-plugins/aiworker-video-command/index.js',
  './openclaw-plugins/aiworker-video-command/openclaw.plugin.json',
  './openclaw-plugins/aiworker-video-command/package.json',
  './openclaw-plugins/aiworker-video-command/lib/**/*',
  './openclaw-plugins/aiworker-video-command/scripts/**/*',
  './openclaw-skills/aiworker-director-brain/SKILL.md',
  './openclaw-skills/aiworker-task-flow/SKILL.md',
  './openclaw-skills/aiworker-task-flow/WORKSPACE_*.md',
  './openclaw-skills/aiworker-task-flow/lib/**/*',
  './openclaw-skills/aiworker-task-flow/scripts/**/*',
  './ops/feishu-director-brain/schema.json',
]

const standaloneDevelopmentExcludes = [
  './.tmp',
  './.tmp/**/*',
  './output',
  './output/**/*',
  './test-results',
  './test-results/**/*',
  './playwright-report',
  './playwright-report/**/*',
  './coverage',
  './coverage/**/*',
  './tests',
  './tests/**/*',
  './src',
  './src/**/*',
  './src-tauri',
  './src-tauri/**/*',
  './docs',
  './docs/**/*',
  './wiki',
  './wiki/**/*',
  './skills',
  './skills/**/*',
  './launch-agents',
  './launch-agents/**/*',
  './scripts/e2e-openclaw',
  './scripts/e2e-openclaw/**/*',
  './scripts/director-brain-test-fixture.mjs',
  './openclaw-plugins/**/test',
  './openclaw-plugins/**/test/**/*',
  './openclaw-skills/**/test',
  './openclaw-skills/**/test/**/*',
  './ops/n8n',
  './ops/n8n/**/*',
  './ops/platform',
  './ops/platform/**/*',
  './**/.cache',
  './**/.cache/**/*',
  './**/.pytest_cache',
  './**/.pytest_cache/**/*',
  './**/__pycache__',
  './**/__pycache__/**/*',
  './**/*.db',
  './**/*.db-*',
  './**/*.sqlite',
  './**/*.sqlite-*',
  './**/*.sqlite3',
  './**/*.sqlite3-*',
  './**/*.log',
  './**/*.pid',
  './**/*.tsbuildinfo',
  './AGENTS.md',
  './CLAUDE.md',
  './CHANGELOG.md',
  './CODE_OF_CONDUCT.md',
  './CONTRIBUTING.md',
  './README.md',
  './RELEASE.md',
  './SECURITY.md',
  './SKILL.md',
  './Dockerfile',
  './docker-compose*.yml',
  './docker-entrypoint.sh',
  './install.sh',
  './install.ps1',
  './OpenClaw Profiles Desktop.command',
  './eslint.config.mjs',
  './playwright*.config.ts',
  './vitest.config.ts',
  './tsconfig*.json',
  './tailwind.config.js',
  './postcss.config.js',
  './pnpm-lock.yaml',
  './pnpm-workspace.yaml',
]

/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
  outputFileTracingIncludes: {
    '/*': standaloneRuntimeIncludes,
  },
  outputFileTracingExcludes: {
    '/*': [
      ...standaloneDevelopmentExcludes,
      './.data/**/*',
      './.PhoenixBrain',
      './.git',
      './.git/**/*',
      './.env*',
      './**/.PhoenixBrain',
      './**/.git',
      './**/.git/**/*',
      './**/.env*',
      './.npmrc',
      './.netrc',
      './.pypirc',
      './.git-credentials',
      './.ssh',
      './.ssh/**/*',
      './id_rsa',
      './id_ed25519',
      './*.pem',
      './*.key',
      './*.p12',
      './*.pfx',
      './**/.npmrc',
      './**/.netrc',
      './**/.pypirc',
      './**/.git-credentials',
      './**/.ssh',
      './**/.ssh/**/*',
      './**/id_rsa',
      './**/id_ed25519',
      './**/*.pem',
      './**/*.key',
      './**/*.p12',
      './**/*.pfx',
      './**/test-catalog.json',
    ],
  },
  // Keep Next/Turbopack inside the canonical repository even when a parent
  // operations directory contains an unrelated package-lock.json.
  turbopack: { root: __dirname },
  // A release directory is immutable. Keep ISR/fetch cache in memory and serve
  // local public images directly so runtime requests never create .next/cache.
  experimental: { isrFlushToDisk: false },
  images: { unoptimized: true },
  // Transpile ESM-only packages so they resolve correctly in all environments
  transpilePackages: ['react-markdown', 'remark-gfm'],
  
  // Security headers
  // Content-Security-Policy is set in src/proxy.ts with a per-request nonce.
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          { key: 'X-Frame-Options', value: 'DENY' },
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
          ...(process.env.NODE_ENV === 'production' && process.env.MC_DISABLE_HSTS !== '1' || process.env.MC_ENABLE_HSTS === '1' ? [
            { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' }
          ] : []),
        ],
      },
    ];
  },
  
};

module.exports = withNextIntl(nextConfig);
